openapi: 3.0.1
info:
  title: Shelly Gen1 REST API
  version: 1.0.0
paths:
  /shelly:
    description: The HTTP method used for performing any of the requests below is intentionally ignored. Most endpoints will always return their specific JSON payload and perform actions if query parameters are specified.
    get:
      tags:
        - common-http-api
      operationId: http-dialect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /settings:
    description: Shelly Plug/PlugS supports up to 20 schedule rules.
    get:
      tags:
        - shelly-plug-plugs
      operationId: shelly-plug-plugs-overview
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  max_power:
                    type: number
                    description: Overpower threshold in Watts
                  led_status_disable:
                    type: boolean
                    description: <strong>PlugS only</strong> Disable LED indication for network status
                  led_power_disable:
                    type: boolean
                    description: <strong>PlugS only</strong> Disable LED indication for output status
                  actions:
                    type: string
                    description: 'For setting actions, see <a href="https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs-settings-actions"><code>/settings/actions</code></a>'
    parameters:
      - name: max_power
        in: query
        description: Overpower threshold in Watts
        schema:
          type: number
      - name: led_status_disable
        in: query
        description: <strong>PlugS only</strong> Disable LED indication for network status
        schema:
          type: boolean
      - name: led_power_disable
        in: query
        description: <strong>PlugS only</strong> Disable LED indication for output status
        schema:
          type: boolean
      - name: actions
        in: query
        description: 'For setting actions, see <a href="https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs-settings-actions"><code>/settings/actions</code></a>'
        schema:
          type: string
  /settings/ap:
    description: Provides information about the current WiFi AP configuration and allows changes. The returned document is identical to the one returned by <code>/settings</code> in the <code>wifi_ap</code> key. Shelly devices do not allow the SSID for AP WiFi mode to be changed.
    get:
      tags:
        - common-http-api
      operationId: settings-ap
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: Set to <code>1</code> to return the device to AP WiFi mode
                  key:
                    type: string
                    description: WiFi password required for association with the device's AP
    parameters:
      - name: enabled
        in: query
        description: Set to <code>1</code> to return the device to AP WiFi mode
        schema:
          type: boolean
      - name: key
        in: query
        description: WiFi password required for association with the device's AP
        schema:
          type: string
  /settings/sta:
    description: Provides information about the current WiFi Client mode configuration and allows changes. The returned document is identical to the one returned by <code>/settings</code> in the <code>wifi_sta</code> key.
    get:
      tags:
        - common-http-api
      operationId: settings-sta
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: Set to <code>1</code> to make STA the current WiFi mode
                  ssid:
                    type: string
                    description: The WiFi SSID to associate with
                  key:
                    type: string
                    description: The password required for associating to the given WiFi SSID
                  ipv4_method:
                    type: string
                    description: <code>dhcp</code> or <code>static</code>
                  ip:
                    type: string
                    description: Local IP address if <code>ipv4_method</code> is <code>static</code>
                  netmask:
                    type: string
                    description: Mask if <code>ipv4_method</code> is <code>static</code>
                  gateway:
                    type: string
                    description: Local gateway IP address if <code>ipv4_method</code> is <code>static</code>
                  dns:
                    type: string
                    description: DNS address if <code>ipv4_method</code> is <code>static</code>
    parameters:
      - name: enabled
        in: query
        description: Set to <code>1</code> to make STA the current WiFi mode
        schema:
          type: boolean
      - name: ssid
        in: query
        description: The WiFi SSID to associate with
        schema:
          type: string
      - name: key
        in: query
        description: The password required for associating to the given WiFi SSID
        schema:
          type: string
      - name: ipv4_method
        in: query
        description: <code>dhcp</code> or <code>static</code>
        schema:
          type: string
      - name: ip
        in: query
        description: Local IP address if <code>ipv4_method</code> is <code>static</code>
        schema:
          type: string
      - name: netmask
        in: query
        description: Mask if <code>ipv4_method</code> is <code>static</code>
        schema:
          type: string
      - name: gateway
        in: query
        description: Local gateway IP address if <code>ipv4_method</code> is <code>static</code>
        schema:
          type: string
      - name: dns
        in: query
        description: DNS address if <code>ipv4_method</code> is <code>static</code>
        schema:
          type: string
  /settings/login:
    description: 'HTTP authentication configuration: <code>enabled</code> flag, credentials. <code>unprotected</code> is initially false and is used by the user interface to show a warning when auth is disabled. If the user wants to keep using Shelly without a password, they can set <code>unprotected</code> to hide the warning.'
    get:
      tags:
        - common-http-api
      operationId: settings-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: Whether to require HTTP authentication
                  unprotected:
                    type: boolean
                    description: Whether the user is aware of the risks
                  username:
                    type: string
                    description: Length between 1 and 50
                  password:
                    type: string
                    description: Length between 1 and 50
    parameters:
      - name: enabled
        in: query
        description: Whether to require HTTP authentication
        schema:
          type: boolean
      - name: unprotected
        in: query
        description: Whether the user is aware of the risks
        schema:
          type: boolean
      - name: username
        in: query
        description: Length between 1 and 50
        schema:
          type: string
      - name: password
        in: query
        description: Length between 1 and 50
        schema:
          type: string
  /settings/cloud:
    description: 'Can set the <code>enabled</code> (connect to cloud) flag. When set, Shelly will keep a secure connection to Allterco''s servers and allow monitoring and control from anywhere.'
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /settings/actions:
    description: 'Shelly Plug/PlugS supports the following actions, which can be set as described at <a href="https://shelly-api-docs.shelly.cloud/#settings-actions"><code>/settings/actions</code></a>:'
    get:
      tags:
        - shelly-plug-plugs
      responses:
        '200':
          description: OK
  /status:
    description: Shelly Plug adds information about the current state of the plug (ON or OFF) and instantaneous power reading in Watts.
    get:
      tags:
        - shelly-plug-plugs
      operationId: shelly-plug-plugs-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /reboot:
    description: When requested will cause a reboot of the device.
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /ota:
    description: Provides information about the device firmware version and the ability to trigger an over-the-air update.
    get:
      tags:
        - common-http-api
      operationId: ota
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: Run firmware update from specified URL
                  update:
                    type: boolean
                    description: Run firmware update from default URL
                  beta:
                    type: boolean
                    description: Run firmware update from beta URL (if available)
    parameters:
      - name: url
        in: query
        description: Run firmware update from specified URL
        schema:
          type: string
      - name: update
        in: query
        description: Run firmware update from default URL
        schema:
          type: boolean
      - name: beta
        in: query
        description: Run firmware update from beta URL (if available)
        schema:
          type: boolean
  /ota/check:
    description: Manual check for new firmware version.
    get:
      tags:
        - common-http-api
      operationId: ota-check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /wifiscan:
    description: Only available when in AP mode. Starts a WiFi scan and provides information about found networks.
    get:
      tags:
        - common-http-api
      operationId: wifiscan
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /debug/log:
    description: Retrieve debug log file 0
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /debug/log1:
    description: Retrieve debug log file 1
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /cit/d:
    description: Get CoIoT description package over HTTP
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /sta_cache_reset:
    description: 'Reset STA cache: only applicable on devices which support STA caching (battery operated devices Shelly Door/Window 1/2, Shelly H&amp;T, Shelly Smoke, Shelly Flood, Shelly Button1)'
    get:
      tags:
        - common-http-api
      responses:
        '200':
          description: OK
  /settings/relay/0:
    description: The returned document here is identical to the data returned in <code>/settings</code> for the single output channel in the <code>relays</code> array. The channel index exists to preserve API compatibility with multi-channel Shelly devices. Attributes in the response match the set of accepted parameters.
    get:
      tags:
        - shelly-plug-plugs
      operationId: shelly-plug-plugs-settings-relay-0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Set relay name
                  appliance_type:
                    type: string
                    description: Set custom configurable appliance type
                  reset:
                    type: object
                    description: Submitting a non-empty value will reset settings for the plug output to factory defaults
                  default_state:
                    type: string
                    description: 'Accepted values: <code>off</code>, <code>on</code>, <code>last</code>'
                  auto_on:
                    type: number
                    description: 'Automatic flip back timer, seconds. Will engage after turning the plug OFF'
                  auto_off:
                    type: number
                    description: 'Automatic flip back timer, seconds. Will engage after turning the plug ON'
                  schedule:
                    type: boolean
                    description: Enable schedule timer
                  schedule_rules:
                    type: array
                    items:
                      type: string
                    description: 'Rules for schedule activation, e.g. <code>0000-0123456-on</code>'
                  max_power:
                    type: number
                    description: Overpower threshold in Watts
    parameters:
      - name: name
        in: query
        description: Set relay name
        schema:
          type: string
      - name: appliance_type
        in: query
        description: Set custom configurable appliance type
        schema:
          type: string
      - name: reset
        in: query
        description: Submitting a non-empty value will reset settings for the plug output to factory defaults
        schema:
          type: object
      - name: default_state
        in: query
        description: 'Accepted values: <code>off</code>, <code>on</code>, <code>last</code>'
        schema:
          type: string
      - name: auto_on
        in: query
        description: 'Automatic flip back timer, seconds. Will engage after turning the plug OFF'
        schema:
          type: number
      - name: auto_off
        in: query
        description: 'Automatic flip back timer, seconds. Will engage after turning the plug ON'
        schema:
          type: number
      - name: schedule
        in: query
        description: Enable schedule timer
        schema:
          type: boolean
      - name: schedule_rules
        in: query
        description: 'Rules for schedule activation, e.g. <code>0000-0123456-on</code>'
        schema:
          type: array
          items:
            type: string
      - name: max_power
        in: query
        description: Overpower threshold in Watts
        schema:
          type: number
  /meter/0:
    description: Shows current status of the output channel and accepts commands for controlling the channel.
    get:
      tags:
        - shelly-plug-plugs
      operationId: shelly-plug-plugs-meter-0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turn:
                    type: string
                    description: 'Accepted values are <code>on</code>, <code>off</code>, <code>toggle</code>. This will turn ON/OFF the respective output channel when request is sent'
                  timer:
                    type: number
                    description: A one-shot flip-back timer in seconds
    parameters:
      - name: turn
        in: query
        description: 'Accepted values are <code>on</code>, <code>off</code>, <code>toggle</code>. This will turn ON/OFF the respective output channel when request is sent'
        schema:
          type: string
      - name: timer
        in: query
        description: A one-shot flip-back timer in seconds
        schema:
          type: number